- hosts: lxc-webserver
  remote_user: root
  tasks:
  - name: Gunicornのインストール
    apt: name=gunicorn3 state=latest

  - name: Pyramidのインストール
    apt: name=python3-pyramid state=latest

  - name: ユーザーpyramidを作成・切り替え
    user: name=pyramid comment="Management pyramid" shell=/bin/dash

# TODO: Pyramidアプリの導入
# TODO: Gunicornの起動
